language: ruby

rvm:
  - 2.4

script: ./script/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch
  - dev

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./_site
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master