# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
- raw/*
- publi.sh
- script/*

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- jekyll-polyglot

# 3. Gem settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: ACMAH # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: ACMAH # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/acmah.org

# Polyglot
languages: ["ca", "es"]
default_lang: "ca"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Madrid # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "ACMAH" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/acmah-logo.png" # Site logo, also used in jekyll-seo-tag
description: "Som una entitat sense ànim de lucre, amb un projecte associatiu que té com a eix principal el treball amb les famílies que conviuen amb afectats per la malaltia de Huntington." # Site description and default description, also used in jekyll-seo-tag
url: "https://malcp.github.io" # Site url, also used in jekyll-seo-tag
baseurl: "/acmah.org"
github:
  url: https://malcp.github.io/acmah.org # Site url, also used in jekyll-seo-tag. Automatically overriden by github pages
repo: "https://github.com/malcp/acmah.org"
email: "@gmail.com"
disqus: "acmah-1"
avatarurl: "/assets/favicon.ico" # "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Services: /services/
  News: /news/
  #  Element: elements/
  Blog: /blog/
navigation_header_locales:
  Home:
          ca: Inici
          es: Inicio
  Services:
          ca: Serveis
          es: Servicios
  News:
          ca: Notícies
          es: Noticias
  Blog:
          ca: Blog
          es: Blog

navigation_footer:
  Created by malcp: https://github.com/malcp

social_links:
  Facebook: https://www.facebook.com/acmah.org
  #Twitter: https://twitter.com/DavidDarnes
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #GooglePlus: https://plus.google.com/+DavidDarnes
  #GitHub: https://github.com/daviddarnes
  #link: https://darn.es

locales:
  about:
    ca: Sobre nosaltres
    es: Sobre nosotros
  about_desc:
    ca: Som una entitat sense ànim de lucre, amb un projecte associatiu que té com a eix principal el treball amb les famílies que conviuen amb afectats per la malaltia de Huntington.
    es: Somos una entidad sin ánimo de lucro, con un proyecto asociativo que tiene como eje principal el trabajo con las familias que conviven con afectados por la enfermedad de Huntington.
  related_posts:
    ca: Articles relacionats
    es: Articulos relacionados
  latest_posts:
    ca: Últims articles publicats
    es: Últimos articulos publicados
  category:
    event:
      ca: Activitat
      es: Actividad
    general:
      ca: General
      es: General
    news:
      ca: Notícia
      es: Noticia

prose:
  rooturl: ''
  siteurl: 'http://malcp.github.io/acmah.org/'
  relativeLinks: ''
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - /_sass
    - /raw
    - /script
    - .gitignore
    - .travis.yml
    - Gemfile
    - LICENSE
    - README.md
    - _config.yml
    - alembic-jekyll-theme.gemspec
    - publi.sh
    - /blog
  metadata:
    "":
      - name: 'lang'
        field:
          element: 'select'
          label: 'Idioma de la pàgina'
          options:
            - name: 'Català'
              value: 'ca'
            - name: 'Castellà'
              value: 'es'
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Títol"
          placeholder: 'títol de la pàgina'
          value: ""
    _posts:
      - name: 'lang'
        field:
          element: 'select'
          label: 'Idioma de la pàgina'
          options:
            - name: 'Català'
              value: 'ca'
            - name: 'Castellà'
              value: 'es'
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Títol"
          placeholder: 'títol de la pàgina'
          value: ""
      - name: "category"
        field:
          element: 'select'
          label: 'Categoria'
          options:
            - name: 'General'
              value: 'general'
            - name: 'Activitat'
              value: 'event'
            - name: 'Notícia'
              value: 'news'
      - name: "feature_image"
        field:
          element: "text"
          label: "Imatge capçalera"
          placeholder: 'url a una imatge'
          value: "https://unsplash.it/1200/400?image=200"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicat"
          value: false
