# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
- raw/*

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- jekyll-polyglot

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
author: ACMAH # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: ACMAH # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/acmah.org

# Polyglot
languages: ["ca", "es"]
default_lang: "ca"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Madrid # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "ACMAH" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/acmah-logo.png" # Site logo, also used in jekyll-seo-tag
description: "Alembic is a starting point for Jekyll projects. Rather than starting from scratch, this boilerplate is designed to get the ball rolling immediately" # Site description and default description, also used in jekyll-seo-tag
url: "https://ghmap.github.io/jekyll-alembic" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/ghmap/acmah"
email: "marc.alcala@gmail.com"
disqus: "acmah-1"
avatarurl: "/assets/favicon.ico" # "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Services: /services/
  #  Element: /elements/
  Blog: /blog/
navigation_header_locales:
  Home:
          ca: Inici
          es: Inicio
  Services:
          ca: Serveis
          es: Servicios
  Blog:
          ca: Blog
          es: Blog

navigation_footer:
  Created by ghmap: https://github.com/ghmap

social_links:
  Facebook: https://www.facebook.com/acmah.org
  #Twitter: https://twitter.com/DavidDarnes
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #GooglePlus: https://plus.google.com/+DavidDarnes
  #GitHub: https://github.com/daviddarnes
  #link: https://darn.es
